name: api.lavylavender.com

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stack.env
    command: >
      sh -c "pnpm run start:prod"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=4000
    networks:
      - intranet
      - traefik-public
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.swarm.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true

        - traefik.http.services.personal-api.loadbalancer.server.port=4000
        - traefik.http.routers.personal-api.rule=Host(`api.lavylavender.com`)
        - traefik.http.routers.personal-api.entrypoints=http
        - traefik.http.routers.personal-api.middlewares=https-redirect
        - traefik.http.routers.personal-api.entrypoints=https
        - traefik.http.routers.personal-api.service=api

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - intranet
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redisdata:


networks:
  intranet:
    driver: bridge
  traefik-public:
    external: true
