version: "3.9"

services:
  api:
    image: yourusername/api:latest
    command: >
      sh -c "pnpm run start:prod"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=4000
      - AUTHORIZATION_KEY=${AUTHORIZATION_KEY}
      - CALLBACK_URL=${CALLBACK_URL}
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - SPOTIFY_USER_ID=${SPOTIFY_USER_ID}
    networks:
      - intranet
      - traefik-public
    depends_on:
      - redis
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.services.api.loadbalancer.server.port=4000
        - traefik.http.routers.api.rule=Host(`api.lavylavender.com`)
        - traefik.http.routers.api.entrypoints=http
        - traefik.http.routers.api.middlewares=https-redirect
        - traefik.http.routers.api.entrypoints=https
        - traefik.http.routers.api.tls=true

  redis:
    image: redis:6.2-alpine
    networks:
      - intranet
    volumes:
      - redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  redisdata:

networks:
  intranet:
    driver: overlay
    attachable: true
  traefik-public:
    external: true
